### PR TITLE
Fix tests in PR #72, add Travis and Coveralls configuration

### PR DESCRIPTION
**Pull request by PetrDlouhy**
Change the Coveralls api key after pulling this.

### CODE REVIEW

**Comment by jimmykobe1171** [comment]
well, seems like I don't have the right to add this repository to Travis, any ideas? @PetrDlouhy

**Comment by PetrDlouhy** [comment]
It should be connected with GitHub rights. If you are maintaining this repository, you should be able to enable Travis builds on https://travis-ci.org/digi604/django-smart-selects

**Comment by jimmykobe1171** [comment]
@PetrDlouhy  I don't see django-smart-selects in my Travis account since I am not the owner, so I can not turn on Travis on this repository. I click your link and it says it is not an active repository. Maybe I need to ask the owner for help.

**Comment by PetrDlouhy** [comment]
@jimmykobe1171 Well, I don't know. I taught, that rights to the repository would be enough.

**Comment by jimmykobe1171** [comment]
@PetrDlouhy It's weird, I can see the project in coveralls account.

**Comment by PetrDlouhy** [comment]
Did you try to `re-sync repos` on https://coveralls.io/repos/new?

**Comment by jimmykobe1171** [comment]
@PetrDlouhy  The coveralls is ok, I can find the django-smart-select project. But Travis is not ok. I have sent email to Travis, waiting for their reply.

**Comment by PetrDlouhy** [comment]
I am closing this PR, because the PR #109 overcome this one.

**Pull request closed without merging**
