### PR TITLE
Compatibility with Django 1.6 + Python 2.7/3.3

### PR DESCRIPTION
**Pull request by d9pouces**

### CODE REVIEW

**Comment by SalahAdDin** [comment]
@digi604 , Man, i think that you should update your package, is a very useful package , but, is a lot of outdated.

**Comment by SalahAdDin** [comment]
Man, i have this issue, perhaps you can help me:
https://github.com/digi604/django-smart-selects/issues/74

**Comment by SalahAdDin** [comment]
Now, we have the next warning:

```
/home/tulipan/Proyectos/TiempoTurco/lib/python3.4/site-packages/smart_selects/views.py:10: RemovedInDjango19Warning: django.db.models.get_model is deprecated.
  model_class = get_model(app, model)
```

Can anyone fix it?

**Comment by SalahAdDin** [comment]
I RECOMMENDED using this PR to update the package, I upgraded the application today and had me several errors related to db field, in the case of ```basestring``` and conflict with ```empty_label = iterator.next () [1]``` and the cmp variable. Urgent, please do merge.

**Comment by jimmykobe1171** [comment]
fixed in new release 1.1.1

**Comment by SalahAdDin** [comment]
See dad, i'm helping, i'm helping. :D

**Pull request closed without merging**
