### PR TITLE
Moved JS code to an external final supports dynamic inlines

### PR DESCRIPTION
**Pull request by knixeur**
Instead of initializing each field we add attributes to the select items
and use that to initialize all of them later with a global script.
We bind the change even to '#content-main select' so we can handle
dynamic items added later (inlines).

### CODE REVIEW

**Comment by gbonvehi** [comment]
Includes change in #95

**Comment by gbonvehi** [comment]
Last commit amended added missing JS code.

**Comment by blag** [comment]
I just became the GitHub and PyPI maintainer. I'm going to try to merge in a few other PRs tonight. If you rebase this against master I'll merge it in. Thanks!

**Comment by knixeur** [comment]
Hi @blag I'm glad you took over, I've just done a rebase with master. I didn't test the code and there was a major change inbetween where JS was moved to an external script. This change will probably conflict with what I did, I've just tried to make a clean merge, if I've some time next week I'll try to test it. Cheers!

**Comment by blag** [comment]
Hey @knixeur - did you ever get some time to clean this up?

**Comment by knixeur** [comment]
No, sorry @blag, I don't think I'll be able to do it these weeks. Anyway,  I think this branch is obsolete now with the new js code.

**Pull request closed without merging**
