### PR TITLE
Removing contribute_to_class and calling parent classes with super

### PR DESCRIPTION
**Pull request by 000paradox000**
Removing contribute_to_class and calling to IntrospectiveFieldMixin __init__ method using super

### CODE REVIEW

**Comment by blag** [comment]
NAK. Simply removing `contribute_to_class` doesn't fix anything. The intent of having that in the first place was to allow users to use `'self'` or `<app>.<Model>` strings, and we can't resolve that into the actual Model object in `__init__()`.

I like the `super()` stuff though.

Please split out the manifest changes into another PR.

**Comment by 000paradox000** [comment]
maybe the problem is in contributd_to_class because the  variables for model name and app name are overwritten

**Comment by 000paradox000** [comment]
i will try to send a pr tonight giving s better idea of rhe problem thanks a lot for your answer

**Comment by blag** [comment]
I think that's the issue; I'm working on a fix for this now.

**Comment by blag** [comment]
Fixed released on master; needs testing.

And I have confirmed that the static files *are* included when distributed, so I'm closing this PR and keeping #153 open until it's fixed.

Thank you for your help! 😄

**Comment by 000paradox000** [comment]
Thanks a lot for paying attention. Just one suggestion including static files in the manifest files allows people who wants to install a custom fork of this package (python setup.py build).

Thanks again @blag

**Comment by 000paradox000** [comment]
It still not working for me. I don't have recursive models

**Comment by blag** [comment]
Post your `models.py` please.

**Comment by 000paradox000** [comment]
class Especie(BaseModel):
    name = models.CharField(verbose_name=u"Nombre", max_length=200)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"especies"
        verbose_name = u"especie"
        ordering = ['name',]


class Raza(BaseModel):
    name = models.CharField(verbose_name=u"Nombre", max_length=200)
    especie = models.ForeignKey(Especie, verbose_name=u"Especie")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"razas"
        verbose_name = u"raza"
        ordering = ['name', ]


class Mascota(BaseModel):
    especie = models.ForeignKey(Especie)

    raza = ChainedForeignKey(
        Raza,
        chained_field="especie",
        chained_model_field="especie"
    )

    name = models.CharField(verbose_name=u"Nombre", max_length=200)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"mascotas"
        verbose_name = u"mascota"
        ordering = ['name', ]

**Comment by 000paradox000** [comment]
`class Especie(BaseModel):
    name = models.CharField(verbose_name=u"Nombre", max_length=200)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"especies"
        verbose_name = u"especie"
        ordering = ['name',]


class Raza(BaseModel):
    name = models.CharField(verbose_name=u"Nombre", max_length=200)
    especie = models.ForeignKey(Especie, verbose_name=u"Especie")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"razas"
        verbose_name = u"raza"
        ordering = ['name', ]


class Mascota(BaseModel):
    especie = models.ForeignKey(Especie)

    raza = ChainedForeignKey(
        Raza,
        chained_field="especie",
        chained_model_field="especie"
    )

    name = models.CharField(verbose_name=u"Nombre", max_length=200)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"mascotas"
        verbose_name = u"mascota"
        ordering = ['name', ]
`

**Comment by 000paradox000** [comment]
```class Especie(BaseModel):
    name = models.CharField(verbose_name=u"Nombre", max_length=200)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"especies"
        verbose_name = u"especie"
        ordering = ['name',]


class Raza(BaseModel):
    name = models.CharField(verbose_name=u"Nombre", max_length=200)
    especie = models.ForeignKey(Especie, verbose_name=u"Especie")

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"razas"
        verbose_name = u"raza"
        ordering = ['name', ]


class Mascota(BaseModel):
    especie = models.ForeignKey(Especie)

    raza = ChainedForeignKey(
        Raza,
        chained_field="especie",
        chained_model_field="especie"
    )

    name = models.CharField(verbose_name=u"Nombre", max_length=200)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = u"mascotas"
        verbose_name = u"mascota"
        ordering = ['name', ]
```

**Comment by 000paradox000** [comment]
Please include a recursive example in the readme for giving a better idea of the improvements

**Comment by blag** [comment]
The improvement done in this PR was to allow users to specify related models as strings, just like normal vanilla Django `ForeignKey` objects:

```python
class TreeNode(models.Model):
    parent = ChainedForeignKey('self', ...)
```

Since this PR simply helps D-S-S more closely mirror the behavior of vanilla Django `ForeignKey` usage, I figured I didn't really need to document it very much.

Also, I'm not a Python packaging wizard - I installed D-S-S with `pip install django-smart-selects`, and when I dig through the installed packages in my virtualenv, I find the static files right where I expect them: in the `<virtualenvdir>/smart_selects/static/smart-selects/admin/js` directory. If you build the package with `python setup.py build`, do those static files not get included?

**Comment by 000paradox000** [comment]
Yes they're not included

**Comment by 000paradox000** [comment]
Also if you make pip install git+https://FORK-URL it does not include static files

**Comment by blag** [comment]
Ah, gotcha, I'll incorporate the changes to the manifest then. Would the changes you proposed fix the `pip install git+https://...` not including static files as well?

**Comment by blag** [comment]
Can you post the network traces from your browser's developer tools, including the payloads of any AJAX requests and responses? Does the admin page properly create the AJAX request? Does the server run into any issues constructing the AJAX response? What's the HTTP status code on the AJAX response? And the AJAX response payload?

**Comment by 000paradox000** [comment]
With 1.2.6 now all is working perfect thanks @blag

**Pull request closed without merging**
