### PR TITLE
chainedm2m with proper selected highlighting

### PR DESCRIPTION
**Pull request by adam-tokarski**

### CODE REVIEW

**Comment by blag** [comment]
I have zero context for this. Can you tell me what this is fixing or improving?

**Comment by adam-tokarski** [comment]
Sure, sorry if I should create issue before, but the case it that ChainedM2M is no rendering previously selected options.

**Comment by blag** [comment]
Nah, don't bother creating an issue. A good initial description would have been nice though. 😉 

Thanks!

**Comment by omidraha** [comment]
Thanks for fixing this issue,
But current `1.2.6` version on the `pypi` doesn't updated for that yet.
Please update `pypi` for this issue.

This is a scenario that is exactly related to this issue, when we use `ForeignKey` on the `Writer` model:

```

class Publication(models.Model):
    name = models.CharField(max_length=255)


class Writer(models.Model):
    class Meta:
        unique_together = ['name', 'publications']

    name = models.CharField(max_length=255)
    publication = models.ForeignKey('Publication')


class Book(models.Model):
    publication = models.ForeignKey(Publication)
    writer = ChainedManyToManyField(
        Writer,
        chained_field="publication",
        chained_model_field="publication",
    )
    name = models.CharField(max_length=255)

```

**Comment by adam-tokarski** [comment]
As I've just verified, it should be working with `1.2.7` which is actually on PyPI.

**Pull request merged**
