### PR TITLE
Fix basestring error.

### PR DESCRIPTION
**Pull request by SalahAdDin**
Fix base string error.

### CODE REVIEW

**Comment by blag** [comment]
So this looks like it helps Python 2/3 compatibility, but where is this an issue? The Travis tests all seem to be passing without this...

**Comment by blag** [comment]
Also, using six would be preferable.

**Comment by SalahAdDin** [comment]
Fell free to change it :D

**Comment by blag** [comment]
I don't understand how this PR helps. Is `unicode`, `str`, `bytes`, or `basestring` imported from `db_fields.py`? All Travis tests are passing, so this doesn't seem to fix anything, it's just adding string definitions for little gain. As such, I'm closing this until it can be demonstrated that this fixes an issue. Thanks for your help though! 😄

**Pull request closed without merging**
