### PR TITLE
Implement ChainedManyToMany

### PR DESCRIPTION
**Pull request by cormier**
# ChainedManyToMany

## Status
There has been some requests -- for example #38 and #35 -- for the implementation support for a `ChainedManyToMany` field. This is an **imperfect attempt** at implementing a `ChainedManyToMany`. It works well, but I do not expect this PR to be merged in its current form because it still needs some cleanup. I am submitting it in it's current form because I believe this commit may be useful for anyone needing a `ChainedManyToMany` at the moment.

I will gladly appreciate any help in finishing the implementation. If you want to help, please look at the Known Issues, or just review and comment! :smile: 

## Usage
The `ChainedManyToMany` is to be used like the regular `ChainedForeignKey`. For example, if multiple countries were to be selected in the `README` example, the code could be changed to this:

```python
    countries = ChainedManyToManyField(
        Country,
        chained_field="continent",
        chained_model_field="countries",
    )
```
Value | Usage
------------ | -------------
`chained_field` | Field on same model this field should be chained to
`chained_model_field` | Field the values should be saved to (most probably the *through* field)

## Known issues
These issues *should be fixed* before this contribution is merged in the project
* Server side `ChainedManyToMany` clean is **disabled**. 
* This implementation is most probably suboptimal and should be cleaned. There is probably some code that still belongs to `ChainedForeignKey` in here.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Can anyone merge it?

**Comment by cormier** [comment]
@SalahAdDin my intention was to merge it upstream. If you wish to use this feature, you can clone our repo at https://github.com/savoirfairelinux/django-smart-selects

**Comment by SalahAdDin** [comment]
But, other fork have other features, compatibility with python3.4, i think that merge both will be great.

**Comment by cormier** [comment]
@SalahAdDin I think this is all great, but do we know why these features are not merged in this project? Ideally we would have one project that contains all these feature

**Comment by SalahAdDin** [comment]
Well, the problem is that this project's author seems that don't have interests in update this project.

**Comment by digi604** [comment]
Anybody want to take over as maintainer?

**Comment by cormier** [comment]
@digi604: do you mean take over as maintainer of the project or as maintainer for this particular area of the code ?

If you wish to pass over this project, I think that a good thing to do would be to create a specific issue for this. It would be possible to ask the persons who have been forking this project directly and see if anyone has interest in taking over.

**Comment by cormier** [comment]
I saw that @jimmykobe1171 has merged pull requests recently: is he the new maintainer ? Would you be interested in working with me towards getting this PR merged?

**Comment by SalahAdDin** [comment]
Yes, is right :+1:

**Comment by jimmykobe1171** [comment]
Yes, I am. It's a good feature, lets merge it ! I will have a look in a couple of days, thanks for your efforts !

**Comment by SalahAdDin** [comment]
:+1: thanks.

**Comment by arkadyzalko** [comment]
Hi, anyone merge this? I want to help.

**Comment by jimmykobe1171** [comment]
Hi @arkadyzalko , I merged it on branch issue_fix, which includes the latest features and bug fix. Maybe you can have a try there? I will merge it to master ASAP. Sorry for my late operation.

**Comment by SalahAdDin** [comment]
:+1:

**Comment by arkadyzalko** [comment]
I'm going to try this. Thanks!

**Comment by SalahAdDin** [comment]
@digi604 This will be very useful!

**Comment by arkadyzalko** [comment]
Hi,

I've installed but I got this =(:
```
NoReverseMatch at /myapp/myuser/91/
Reverse for 'chained_filter' with arguments '()' and keyword arguments '{'field': 'company', 'app': 'myapp', 'model': 'Department', 'value': '1'}' not found. 2 pattern(s) tried: ['chaining/filter/(?P<app>[\\w\\-]+)/(?P<model>[\\w\\-]+)/(?P<manager>[\\w\\-]+)/(?P<field>[\\w\\-]+)/(?P<foreign_key_app_name>[\\w\\-]+)/(?P<foreign_key_model_name>[\\w\\-]+)/(?P<foreign_key_field_name>[\\w\\-]+)/(?P<value>[\\w\\-]+)/$', 'chaining/filter/(?P<app>[\\w\\-]+)/(?P<model>[\\w\\-]+)/(?P<field>[\\w\\-]+)/(?P<foreign_key_app_name>[\\w\\-]+)/(?P<foreign_key_model_name>[\\w\\-]+)/(?P<foreign_key_field_name>[\\w\\-]+)/(?P<value>[\\w\\-]+)/$']
Request Method:	GET
Request URL:	http://localhost:8000/myapp/myuser/91/
Django Version:	1.8
Exception Type:	NoReverseMatch
Exception Value:	
Reverse for 'chained_filter' with arguments '()' and keyword arguments '{'field': 'company', 'app': 'myapp', 'model': 'Department', 'value': '1'}' not found. 2 pattern(s) tried: ['chaining/filter/(?P<app>[\\w\\-]+)/(?P<model>[\\w\\-]+)/(?P<manager>[\\w\\-]+)/(?P<field>[\\w\\-]+)/(?P<foreign_key_app_name>[\\w\\-]+)/(?P<foreign_key_model_name>[\\w\\-]+)/(?P<foreign_key_field_name>[\\w\\-]+)/(?P<value>[\\w\\-]+)/$', 'chaining/filter/(?P<app>[\\w\\-]+)/(?P<model>[\\w\\-]+)/(?P<field>[\\w\\-]+)/(?P<foreign_key_app_name>[\\w\\-]+)/(?P<foreign_key_model_name>[\\w\\-]+)/(?P<foreign_key_field_name>[\\w\\-]+)/(?P<value>[\\w\\-]+)/$']
Exception Location:	/usr/local/lib/python2.7/dist-packages/django/core/urlresolvers.py in _reverse_with_prefix, line 496
Python Executable:	/usr/bin/python2.7
Python Version:	2.7.6
Python Path:	
['/home/ubuntu/Projects/webapp',
 '/home/ubuntu/Projects/webapp/src/django-smart-selects',
 '/home/ubuntu/Projects/webapp',
 '/usr/lib/python2.7',
 '/usr/lib/python2.7/plat-x86_64-linux-gnu',
 '/usr/lib/python2.7/lib-tk',
 '/usr/lib/python2.7/lib-old',
 '/usr/lib/python2.7/lib-dynload',
 '/usr/local/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages',
 '/usr/lib/python2.7/dist-packages/PILcompat',
 '/usr/lib/python2.7/dist-packages/gtk-2.0',
 '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
```

class MyUser(AbstractMyUser):
 ...
    client = models.ForeignKey('Client', null=True, verbose_name=_('Client'),
                               related_name='users', on_delete=models.SET_NULL)

    company = ChainedForeignKey('myapp.Company',
                                   chained_field="client",
                                   chained_model_field='client', null=True, show_all=False,
                                   verbose_name=_('Company'), on_delete=models.SET_NULL)
    departments = ChainedManyToManyField('myApp.Department',
                                         chained_field='company',
                                         chained_model_field='company',
                                         show_all=False,
                                         verbose_name=_('Departments'))
...

**Comment by arkadyzalko** [comment]
```
/home/ubuntu/Projects/webapp/src/django-smart-selects/smart_selects/widgets.py in render
                    url = URL_PREFIX + ("/".join(reverse(view_name, kwargs=kwargs).split("/")[:-2])) ...
▶ Local vars
```

**Comment by jimmykobe1171** [comment]
Hi all,

I have merged this ChainManyToMany feature and fixed the conflict. Now it is on the branch issue_fix, and will be merged to master after some refactor. Sorry for my late response.

Best,
Jimmy

**Comment by SalahAdDin** [comment]
Thank you very much man, i hope that this app will grow.

**Comment by jimmykobe1171** [comment]
It has been included in the new release 1.2.0 :)

**Comment by SalahAdDin** [comment]
Did you release?

**Comment by jimmykobe1171** [comment]
@SalahAdDin yes, version 1.2.0

**Comment by arkadyzalko** [comment]
thanks!

**Pull request merged**
