### PR TITLE
Adds test script and basic tests of deconstruct() methods, fixes CachedStaticFilesStorage collectstatic crash

### PR DESCRIPTION
**Pull request by joelcrocker**
deconstruct() methods won't work on Django  versions < 1.7, so these tests are skipped when not running on Django 1.7+.

### CODE REVIEW

**Comment by SalahAdDin** [comment]
Can anyone merge it?
Please, try to do pull request in https://github.com/d9pouces/django-smart-selects, maybe he can merge the pull request.

**Comment by joelcrocker** [comment]
@digi604 can this be merged? I want to submit a PR that fixes a crash bug with Django 1.7+ app loading while running collectstatic when using Django's `CachedStaticFilesStorage`, and that PR's commit has the commits in this PR as ancestors.

**Comment by joelcrocker** [comment]
Traceback of the crash the latest commit on this PR fixes:

On a staging server, with DEBUG = False and using Django's CachedStaticFilesStorage, doing an initial deploy (deploying to existing servers created pre-Django 1.7 hasn't been a problem):

```python
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/user/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/home/user/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/home/user/venv/local/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/user/venv/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/user/venv/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/my_project/my_app/models.py", line 15, in <module>
    from smart_selects.db_fields import ChainedForeignKey
  File "/home/user/venv/local/lib/python2.7/site-packages/smart_selects/db_fields.py", line 10, in <module>
    from smart_selects import form_fields
  File "/home/user/venv/local/lib/python2.7/site-packages/smart_selects/form_fields.py", line 5, in <module>
    from smart_selects.widgets import ChainedSelect
  File "/home/user/venv/local/lib/python2.7/site-packages/smart_selects/widgets.py", line 25, in <module>
    class ChainedSelect(Select):
  File "/home/user/venv/local/lib/python2.7/site-packages/smart_selects/widgets.py", line 39, in ChainedSelect
    class Media:
  File "/home/user/venv/local/lib/python2.7/site-packages/smart_selects/widgets.py", line 46, in Media
    js = [static('admin/js/%s' % url) for url in js]
  File "/home/user/venv/local/lib/python2.7/site-packages/django/contrib/admin/templatetags/admin_static.py", line 17, in static
    return _static(path)
  File "/home/user/venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/templatetags/staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "/home/user/venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 128, in url
    hashed_name = self.stored_name(clean_name)
  File "/home/user/venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 277, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/home/user/venv/local/lib/python2.7/site-packages/django/contrib/staticfiles/storage.py", line 91, in hashed_name
    (clean_name, self))
ValueError: The file 'admin/js/jquery.min.js' could not be found with <django.contrib.staticfiles.storage.CachedStaticFilesStorage object at 0x4b55ed0>.
```

**Comment by SalahAdDin** [comment]
Well, the problem is that this project's author seems that don't have interests in update this project.

**Comment by digi604** [comment]
anybody wants to take over as a maintainer?

**Comment by PetrDlouhy** [comment]
Hi, it would be great, if this project has a few tests! What about adding Travis configuration file to run these tests automatically?

**Pull request merged**
