### PR TITLE
fix for Django 1.9: import get_model

### PR DESCRIPTION
**Pull request by PetrDlouhy**

### CODE REVIEW

**Comment by PetrDlouhy** [comment]
Hi, any problem with this PR?

**Comment by psychok7** [comment]
@PetrDlouhy tested your fix and seems to work fine. this project doesn't seem to be mantained anymore..

**Comment by PetrDlouhy** [comment]
I can try to maintain this repository, if @digi604 gave me the rights.

**Comment by halfnibble** [comment]
So....what exactly is going on here? I'd like to see this project maintained--I use it in production. I'm even willing to help maintain it.

**Comment by jimmykobe1171** [comment]
Yes, I am fixing it now, and will be done today. Sorry for the inconvenience.

**Comment by jimmykobe1171** [comment]
Hi all,

This fix has been merged into branch issue_fix, and will be published to master in a few days.

Best,
Jimmy

**Comment by blag** [comment]
Poke.

**Comment by sinansarpe** [comment]
Hi there,
Any news about the fix or the master?
Thank you in advance.

**Comment by halfnibble** [comment]
Thank you so much!

**Comment by jimmykobe1171** [comment]
New version 1.2.0 has been released and it includes this fix :)

**Pull request merged**
