### PR TITLE
This is to fix the jet compatibility 

### PR DESCRIPTION
**Pull request by scrummastermind**
This is a fix for https://github.com/geex-arts/django-jet/issues/67

Please review and merge. Thanks

### CODE REVIEW

**Comment by blag** [comment]
Won't this force all users of django-smart-selects to use the jQuery bundled with Django's admin? Completely negating any effect of the `SMART_SELECTS_USE_DJANGO_JQUERY` settings?

**Comment by scrummastermind** [comment]
@blag No not really as the django.jQuery is set to False by default  the order matters in ||

**Comment by aali-mdsol** [comment]
Was having some issues but digging deeper
USE_DJANGO_JQUERY = False
JQUERY_URL = False
worked 👍

**Comment by scrummastermind** [comment]
Not

**Pull request closed without merging**
